import { example } from './example.js';

const $=s=>document.querySelector(s);
const form=$('#trip-form'); const resultEl=$('#results');
const money=n=>new Intl.NumberFormat('zh-TW').format(n);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={longTransport:'來回交通',localTransport:'當地交通',accommodation:'住宿',food:'餐飲',activities:'活動／雨備',reserve:'預留金'};
let stage=1,current=null,controller=null,enabled=false;
let friendDraft=[{name:'主揪',wish:'',avoid:''},{name:'朋友 A',wish:'',avoid:''},{name:'朋友 B',wish:'',avoid:''},{name:'朋友 C',wish:'',avoid:''}];
const field=n=>form.elements.namedItem(n);
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
field('startDate').min=today;field('endDate').min=today;
const weekend=new Date(today+'T12:00:00Z');weekend.setUTCDate(weekend.getUTCDate()+((6-weekend.getUTCDay()+7)%7));
field('startDate').value=weekend.toISOString().slice(0,10);weekend.setUTCDate(weekend.getUTCDate()+1);field('endDate').value=weekend.toISOString().slice(0,10);
function readTrip(){return {origin:field('origin').value.trim(),destination:field('destination').value,startDate:field('startDate').value,endDate:field('endDate').value,budget:Number(field('budget').value),people:Number(field('people').value),earliest:field('earliest').value,transport:field('transport').value,rooms:field('rooms').value,notes:field('notes').value.trim(),friends:readFriends()};}
function readFriends(){if(stage===2){friendDraft=[...document.querySelectorAll('.friend')].map((el,i)=>({name:el.querySelector('[data-name]').value.trim()||`朋友 ${i+1}`,wish:el.querySelector('[data-wish]').value.trim(),avoid:el.querySelector('[data-avoid]').value.trim()}));}return friendDraft.slice(0,Number(field('people').value));}
function updateTicket(){const t=readTrip();$('#ticket-summary').innerHTML=`<div class="ticket-row"><span>出發 → 目的地</span><strong>${esc(t.origin||'尚未填寫')} → ${esc(t.destination||'一起選')}</strong></div><div class="ticket-row"><span>旅行日期</span><strong>${esc(t.startDate?.slice(5)||'—')} — ${esc(t.endDate?.slice(5)||'—')}</strong></div><div class="ticket-row"><span>同行</span><strong>${esc(t.people)} 位成人</strong></div><div class="ticket-row"><span>節奏</span><strong>${esc(t.earliest)} 後出發</strong></div><div class="ticket-row"><span>交通</span><strong>${t.transport==='public'?'大眾運輸':'自行開車'}</strong></div><div class="ticket-price">$${money(t.budget||0)} <small>/ 人・預算上限</small></div>`;}
function setStage(n){if(stage===2)readFriends();stage=n;$('#trip-fields').hidden=n!==1;$('#friends-fields').hidden=n!==2;$('#step-count').textContent=n===1?'01 / 02':'02 / 02';for(const [i,id] of ['#step-trip','#step-friends'].entries()){const el=$(id);el.classList.toggle('active',n===i+1);if(n===i+1)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');}if(n===2)renderFriends();}
function renderFriends(){const count=Number(field('people').value);while(friendDraft.length<count)friendDraft.push({name:`朋友 ${friendDraft.length}`,wish:'',avoid:''});$('#friends-list').innerHTML=friendDraft.slice(0,count).map((f,i)=>`<div class="friend"><div class="friend-head"><span class="avatar ${['mint','coral','gold','lavender'][i%4]}" aria-hidden="true">${i===0?'揪':i}</span><input data-name aria-label="第 ${i+1} 位朋友暱稱" maxlength="20" value="${esc(f.name)}"></div><div class="field-grid"><label>最期待的事<input data-wish maxlength="180" placeholder="例如：看海、吃在地小吃" value="${esc(f.wish)}"></label><label>最不想要的事<input data-avoid maxlength="180" placeholder="例如：早起、長時間走路" value="${esc(f.avoid)}"></label></div></div>`).join('');}
function error(message){$('#form-error').textContent=message;$('#form-error').hidden=!message;}
function validTrip(){const start=field('startDate'),end=field('endDate');end.setCustomValidity('');const span=(Date.parse(end.value)-Date.parse(start.value))/86400000;if(span<0||span>6)end.setCustomValidity('請選擇 1–7 天，回程不能早於出發。');return [...$('#trip-fields').querySelectorAll('input,select')].every(el=>el.reportValidity());}
$('#next').onclick=()=>{error('');if(validTrip()){setStage(2);$('#workspace').scrollIntoView({behavior:'smooth'});$('#friends-list input').focus({preventScroll:true});}};
$('#back').onclick=()=>setStage(1);
form.addEventListener('input',()=>{error('');updateTicket();if(current){resultEl.hidden=true;current=null;}});
function fill(t){setStage(1);for(const [k,v] of Object.entries(t))if(k!=='friends'&&field(k))field(k).value=v;friendDraft=structuredClone(t.friends);updateTicket();}
$('#open-example').onclick=()=>{if(controller)return;fill(example.trip);showResult(structuredClone(example));};
function busy(on){$('#busy').hidden=!on;document.body.classList.toggle('is-busy',on);form.inert=on;$('#generate').disabled=on;$('#open-example').disabled=on;}
$('#cancel').onclick=()=>controller?.abort();
form.addEventListener('submit',event=>{event.preventDefault();if(stage!==2)return;if(!validTrip())return;generate(readTrip());});
async function generate(trip){
  if(controller)return;error('');resultEl.hidden=true;current=null;controller=new AbortController();busy(true);
  const timeout=setTimeout(()=>controller?.abort('timeout'),115000);
  try{const response=await fetch('/api/travel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(trip),signal:controller.signal});let data;try{data=await response.json();}catch{throw new Error('服務暫時無法回應，請稍後再試。');}if(!response.ok)throw new Error(data.error||'這次未能完成，請重試。');showResult(data);}
  catch(e){error(controller.signal.aborted?'已停止這次產生，你的條件仍保留。':e.message);}
  finally{clearTimeout(timeout);controller=null;busy(false);}
}
function showResult(data){current=data;resultEl.hidden=false;if(data.kind==='comparison'){renderComparison(data);}else{renderPlan(data);}resultEl.scrollIntoView({behavior:'smooth'});resultEl.focus({preventScroll:true});}
function renderComparison(data){resultEl.innerHTML=`<div class="result-top"><div><div class="mode-label">AI 目的地提案 · 先選方向，再排細節</div><h2 id="result-title">這三個地方，各有一個理由。</h2><p class="result-subtitle">依你們的條件比較；房價、座位與總費用仍需確認。</p></div></div><div class="candidate-grid">${data.candidates.map((c,i)=>`<article class="candidate card"><span class="section-kicker">OPTION 0${i+1}</span><h3>${esc(c.destination)}</h3><p>${esc(c.reason)}</p><h4>最值得期待</h4><p>${esc(c.highlight)}</p><h4>需要接受</h4><p>${esc(c.compromise)}</p><p class="notice">${esc(c.budgetNote)}</p><button class="btn btn-hi" data-choice="${i}">選這裡，排完整行程 →</button></article>`).join('')}</div>`;resultEl.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const dest=data.candidates[Number(b.dataset.choice)].destination;let option=[...field('destination').options].find(o=>o.value===dest);if(!option)field('destination').add(new Option(dest,dest));field('destination').value=dest;updateTicket();generate({...data.trip,destination:dest});});}
function renderPlan(data){
const {plan:p,trip:t}=data, demo=data.mode==='example';const total=p.costs.reduce((s,c)=>s+(c.amount??0),0), unknown=p.costs.some(c=>c.amount===null);const leftover=t.budget-total;
const budgetMessage=total>t.budget?`已列金額超出每人預算 $${money(total-t.budget)}，需要調整後再採用。`:unknown?`尚有未報價項目。每人剩餘額度 $${money(leftover)}，不等於已找到這個價格。`:'目前估算在目標內；價格與供應仍需確認，並非可直接訂購的總價。';
resultEl.innerHTML=`<div class="result-top"><div><div class="mode-label">${demo?'介面範例 · 模擬朋友需求 · 非即時 AI 產生':'AI 行程草稿 · 仍需確認票房與價格'}</div><h2 id="result-title">這趟旅行，每個人都有份。</h2><p class="result-subtitle">${esc(t.startDate)} — ${esc(t.endDate)} · ${t.people} 位成人 · 每人目標 NT$${money(t.budget)}</p></div><button class="btn btn-ghost" id="edit-trip">修改條件 ↗</button></div>${demo?'<div class="example-banner">國慶高雄範例：展示介面與安排方式。10/10–11 的車班、房價與營業資訊尚未重新查證，請勿直接據此預訂。</div>':''}<div class="result-deck"><div><div class="plan-hero"><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p><div class="plan-tags"><span>${esc(p.destination)}</span><span>${p.days.length} 天 ${Math.max(0,p.days.length-1)} 夜</span><span>${esc(t.earliest)} 後出發</span><span>${t.transport==='public'?'不開車':'自行開車'}</span></div></div><div class="wish-matches">${p.matches.map(m=>`<article class="match"><small>${esc(t.friends[m.person]?.name||'朋友')} 的願望</small><h4>${esc(t.friends[m.person]?.wish||'一起出門')}</h4><span class="match-status">${{met:'已排入草稿',partial:'需要一點妥協',unmet:'目前未滿足'}[m.status]}</span><p>${esc(m.experience)}</p>${m.tradeoff?`<p>取捨：${esc(m.tradeoff)}</p>`:''}</article>`).join('')}</div>${p.days.map((d,i)=>`<article class="day-card card"><div class="day-head"><span class="day-no">DAY 0${i+1}</span><div><small class="micro">${esc(d.date)} · 規劃時間</small><h3>${esc(d.title)}</h3></div></div>${d.stops.map(s=>`<div class="stop"><span class="time">${esc(s.time)}</span><div><h4>${esc(s.title)}</h4><p>${esc(s.detail)}</p><p>${esc(s.travelNote)}</p><a class="map-link" target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/search/?api=1&amp;query=${encodeURIComponent(s.place)}">查看地點 ↗</a></div></div>`).join('')}</article>`).join('')}</div><aside><section class="budget-card card"><span class="section-kicker">PER PERSON / 整趟每人</span><h3>錢，先算清楚。</h3>${p.costs.map(c=>`<div class="budget-row"><span>${esc(labels[c.category])}<small>${esc(c.note)}</small></span><b>${c.amount===null?'待報價':'$'+money(c.amount)}</b></div>`).join('')}<div class="budget-total">${unknown?'已列金額小計':'目前估算合計'}<br><b>NT$${money(total)}</b>${unknown?' + 待確認項目':''}</div><p class="notice">${esc(budgetMessage)}</p></section><section class="checks-card card"><span class="section-kicker">BEFORE YOU GO</span><h3>出發前，確認這幾件。</h3><ul>${p.checks.map(c=>`<li>${esc(c)}</li>`).join('')}</ul>${p.sources.length?`<div class="sources"><h4>本次搜尋參考</h4>${p.sources.filter(s=>safeUrl(s.url)).map(s=>`<a target="_blank" rel="noopener noreferrer" href="${esc(s.url)}">${esc(s.title)} ↗</a>`).join('')}<p class="micro">來源存在不代表所有內容已人工核實；請開啟原頁確認。</p></div>`:''}</section></aside></div><div class="result-actions"><button class="btn btn-hi" id="share-plan">分享行程摘要 ↗</button><button class="btn btn-ghost" id="copy-plan">複製到群組</button><button class="btn btn-ghost" id="download-plan">下載文字檔</button><button class="btn btn-ghost" id="print-plan">列印／存 PDF</button></div>`;
$('#edit-trip').onclick=()=>{resultEl.hidden=true;current=null;setStage(1);$('#workspace').scrollIntoView({behavior:'smooth'});};
$('#copy-plan').onclick=()=>copyText(shareText(data));
$('#share-plan').onclick=async()=>{const text=shareText(data);if(navigator.share){try{await navigator.share({title:`主揪救星｜${p.destination}`,text});}catch(e){if(e.name!=='AbortError')copyText(text);}}else copyText(text);};
$('#download-plan').onclick=()=>{const blob=new Blob([shareText(data)],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`heiniu-trip-${t.startDate}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);};$('#print-plan').onclick=()=>window.print();
}
function safeUrl(url){try{return new URL(url).protocol==='https:';}catch{return false;}}
function shareText({trip:t,plan:p,mode}){const total=p.costs.reduce((s,c)=>s+(c.amount??0),0);return `${mode==='example'?'【示範草稿・非即時 AI 產生】':'【AI 行程草稿】'} ${p.destination}\n${t.startDate}～${t.endDate}｜${t.people} 位成人｜${t.earliest} 後出發\n每人預算目標 NT$${money(t.budget)}；已列金額 NT$${money(total)}${p.costs.some(c=>c.amount===null)?'，另有待報價項目':''}。並非已確認可訂購的總價。\n\n${p.summary}\n\n${p.matches.map(m=>`${t.friends[m.person]?.name}：${m.experience}${m.tradeoff?'（取捨：'+m.tradeoff+'）':''}`).join('\n')}\n\n${p.days.map((d,i)=>`DAY ${i+1} ${d.date}｜${d.title}\n${d.stops.map(s=>`${s.time} ${s.title}\n${s.detail}\n${s.travelNote}`).join('\n')}`).join('\n\n')}\n\n費用（整趟每人）\n${p.costs.map(c=>`${labels[c.category]}：${c.amount===null?'待報價':'NT$'+money(c.amount)}。${c.note}`).join('\n')}\n\n待確認\n${p.checks.map(c=>'・'+c).join('\n')}\n\n${p.sources.filter(s=>safeUrl(s.url)).map(s=>s.title+' '+s.url).join('\n')}\n主揪救星 · 黑牛工具`;}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('已複製，貼到群組就能一起討論。');}catch{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.left='-9999px';document.body.append(area);area.select();const ok=document.execCommand('copy');area.remove();toast(ok?'已複製行程摘要。':'無法複製，請用下載文字檔。');}}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,3500);}
updateTicket();
fetch('/api/travel').then(r=>r.json()).then(d=>{enabled=d.enabled===true;$('#api-status').textContent=enabled?'AI 規劃已連接。產生的行程仍需核對價格與供應。':'預覽版：AI 規劃尚未開放。可填寫條件、瀏覽高雄範例與分享示範摘要。';}).catch(()=>{$('#api-status').textContent='AI 服務目前無法連線，仍可使用高雄範例預覽。';});
